//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 
namespace GCA.MapToolsExport {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class entry {
        
        private string nullField;
        
        private string javaclassField;
        
        private string stringField;
        
        private string booleanField;
        
        private string intField;
        
        private entryNetrptoolslibMD5Key[] netrptoolslibMD5KeyField;
        
        private entryNetrptoolsmaptoolmodelGUID[] netrptoolsmaptoolmodelGUIDField;
        
        private entryNetrptoolsCaseInsensitiveHashMap_KeyValue[] netrptoolsCaseInsensitiveHashMap_KeyValueField;
        
        private entryNetrptoolsmaptoolmodelMacroButtonProperties[] netrptoolsmaptoolmodelMacroButtonPropertiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @null {
            get {
                return this.nullField;
            }
            set {
                this.nullField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("java-class", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string javaclass {
            get {
                return this.javaclassField;
            }
            set {
                this.javaclassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @string {
            get {
                return this.stringField;
            }
            set {
                this.stringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string boolean {
            get {
                return this.booleanField;
            }
            set {
                this.booleanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @int {
            get {
                return this.intField;
            }
            set {
                this.intField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("net.rptools.lib.MD5Key", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public entryNetrptoolslibMD5Key[] netrptoolslibMD5Key {
            get {
                return this.netrptoolslibMD5KeyField;
            }
            set {
                this.netrptoolslibMD5KeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("net.rptools.maptool.model.GUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public entryNetrptoolsmaptoolmodelGUID[] netrptoolsmaptoolmodelGUID {
            get {
                return this.netrptoolsmaptoolmodelGUIDField;
            }
            set {
                this.netrptoolsmaptoolmodelGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("net.rptools.CaseInsensitiveHashMap_-KeyValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public entryNetrptoolsCaseInsensitiveHashMap_KeyValue[] netrptoolsCaseInsensitiveHashMap_KeyValue {
            get {
                return this.netrptoolsCaseInsensitiveHashMap_KeyValueField;
            }
            set {
                this.netrptoolsCaseInsensitiveHashMap_KeyValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("net.rptools.maptool.model.MacroButtonProperties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public entryNetrptoolsmaptoolmodelMacroButtonProperties[] netrptoolsmaptoolmodelMacroButtonProperties {
            get {
                return this.netrptoolsmaptoolmodelMacroButtonPropertiesField;
            }
            set {
                this.netrptoolsmaptoolmodelMacroButtonPropertiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class entryNetrptoolslibMD5Key {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class entryNetrptoolsmaptoolmodelGUID {
        
        private string baGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string baGUID {
            get {
                return this.baGUIDField;
            }
            set {
                this.baGUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class entryNetrptoolsCaseInsensitiveHashMap_KeyValue {
        
        private string keyField;
        
        private entryNetrptoolsCaseInsensitiveHashMap_KeyValueValue[] valueField;
        
        private entryNetrptoolsCaseInsensitiveHashMap_KeyValueOuterclass[] outerclassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public entryNetrptoolsCaseInsensitiveHashMap_KeyValueValue[] value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outer-class", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public entryNetrptoolsCaseInsensitiveHashMap_KeyValueOuterclass[] outerclass {
            get {
                return this.outerclassField;
            }
            set {
                this.outerclassField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class entryNetrptoolsCaseInsensitiveHashMap_KeyValueValue {
        
        private string classField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class entryNetrptoolsCaseInsensitiveHashMap_KeyValueOuterclass {
        
        private string referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class entryNetrptoolsmaptoolmodelMacroButtonProperties {
        
        private string saveLocationField;
        
        private string indexField;
        
        private string colorKeyField;
        
        private string hotKeyField;
        
        private string commandField;
        
        private string labelField;
        
        private string groupField;
        
        private string sortbyField;
        
        private string autoExecuteField;
        
        private string includeLabelField;
        
        private string applyToTokensField;
        
        private string fontColorKeyField;
        
        private string fontSizeField;
        
        private string minWidthField;
        
        private string maxWidthField;
        
        private string allowPlayerEditsField;
        
        private string toolTipField;
        
        private string commonMacroField;
        
        private string compareGroupField;
        
        private string compareSortPrefixField;
        
        private string compareCommandField;
        
        private string compareIncludeLabelField;
        
        private string compareAutoExecuteField;
        
        private string compareApplyToSelectedTokensField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string saveLocation {
            get {
                return this.saveLocationField;
            }
            set {
                this.saveLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string colorKey {
            get {
                return this.colorKeyField;
            }
            set {
                this.colorKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hotKey {
            get {
                return this.hotKeyField;
            }
            set {
                this.hotKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sortby {
            get {
                return this.sortbyField;
            }
            set {
                this.sortbyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autoExecute {
            get {
                return this.autoExecuteField;
            }
            set {
                this.autoExecuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string includeLabel {
            get {
                return this.includeLabelField;
            }
            set {
                this.includeLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string applyToTokens {
            get {
                return this.applyToTokensField;
            }
            set {
                this.applyToTokensField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fontColorKey {
            get {
                return this.fontColorKeyField;
            }
            set {
                this.fontColorKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fontSize {
            get {
                return this.fontSizeField;
            }
            set {
                this.fontSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string minWidth {
            get {
                return this.minWidthField;
            }
            set {
                this.minWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maxWidth {
            get {
                return this.maxWidthField;
            }
            set {
                this.maxWidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string allowPlayerEdits {
            get {
                return this.allowPlayerEditsField;
            }
            set {
                this.allowPlayerEditsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string toolTip {
            get {
                return this.toolTipField;
            }
            set {
                this.toolTipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string commonMacro {
            get {
                return this.commonMacroField;
            }
            set {
                this.commonMacroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string compareGroup {
            get {
                return this.compareGroupField;
            }
            set {
                this.compareGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string compareSortPrefix {
            get {
                return this.compareSortPrefixField;
            }
            set {
                this.compareSortPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string compareCommand {
            get {
                return this.compareCommandField;
            }
            set {
                this.compareCommandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string compareIncludeLabel {
            get {
                return this.compareIncludeLabelField;
            }
            set {
                this.compareIncludeLabelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string compareAutoExecute {
            get {
                return this.compareAutoExecuteField;
            }
            set {
                this.compareAutoExecuteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string compareApplyToSelectedTokens {
            get {
                return this.compareApplyToSelectedTokensField;
            }
            set {
                this.compareApplyToSelectedTokensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("net.rptools.maptool.model.Token", Namespace="", IsNullable=false)]
    public partial class netrptoolsmaptoolmodelToken {
        
        private string beingImpersonatedField;
        
        private string xField;
        
        private string yField;
        
        private string zField;
        
        private string anchorXField;
        
        private string anchorYField;
        
        private string sizeScaleField;
        
        private string lastXField;
        
        private string lastYField;
        
        private string snapToScaleField;
        
        private string widthField;
        
        private string heightField;
        
        private string scaleXField;
        
        private string scaleYField;
        
        private string snapToGridField;
        
        private string isVisibleField;
        
        private string visibleOnlyToOwnerField;
        
        private string nameField;
        
        private string ownerTypeField;
        
        private string tokenShapeField;
        
        private string tokenTypeField;
        
        private string layerField;
        
        private string propertyTypeField;
        
        private string facingField;
        
        private string isFlippedXField;
        
        private string isFlippedYField;
        
        private string sightTypeField;
        
        private string hasSightField;
        
        private string labelField;
        
        private string notesField;
        
        private string gmNotesField;
        
        private string speechMapField;
        
        private netrptoolsmaptoolmodelTokenID[] idField;
        
        private netrptoolsmaptoolmodelTokenExposedAreaGUID[] exposedAreaGUIDField;
        
        private entry[][] imageAssetMapField;
        
        private entry[][] sizeMapField;
        
        private netrptoolsmaptoolmodelTokenOwnerList[] ownerListField;
        
        private netrptoolsmaptoolmodelTokenPortraitImage[] portraitImageField;
        
        private entry[][] stateField;
        
        private entry[][][] propertyMapCIField;
        
        private entry[][] macroPropertiesMapField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string beingImpersonated {
            get {
                return this.beingImpersonatedField;
            }
            set {
                this.beingImpersonatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string anchorX {
            get {
                return this.anchorXField;
            }
            set {
                this.anchorXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string anchorY {
            get {
                return this.anchorYField;
            }
            set {
                this.anchorYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sizeScale {
            get {
                return this.sizeScaleField;
            }
            set {
                this.sizeScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastX {
            get {
                return this.lastXField;
            }
            set {
                this.lastXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string lastY {
            get {
                return this.lastYField;
            }
            set {
                this.lastYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string snapToScale {
            get {
                return this.snapToScaleField;
            }
            set {
                this.snapToScaleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scaleX {
            get {
                return this.scaleXField;
            }
            set {
                this.scaleXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string scaleY {
            get {
                return this.scaleYField;
            }
            set {
                this.scaleYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string snapToGrid {
            get {
                return this.snapToGridField;
            }
            set {
                this.snapToGridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isVisible {
            get {
                return this.isVisibleField;
            }
            set {
                this.isVisibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string visibleOnlyToOwner {
            get {
                return this.visibleOnlyToOwnerField;
            }
            set {
                this.visibleOnlyToOwnerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ownerType {
            get {
                return this.ownerTypeField;
            }
            set {
                this.ownerTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenShape {
            get {
                return this.tokenShapeField;
            }
            set {
                this.tokenShapeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tokenType {
            get {
                return this.tokenTypeField;
            }
            set {
                this.tokenTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string layer {
            get {
                return this.layerField;
            }
            set {
                this.layerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string propertyType {
            get {
                return this.propertyTypeField;
            }
            set {
                this.propertyTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string facing {
            get {
                return this.facingField;
            }
            set {
                this.facingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isFlippedX {
            get {
                return this.isFlippedXField;
            }
            set {
                this.isFlippedXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isFlippedY {
            get {
                return this.isFlippedYField;
            }
            set {
                this.isFlippedYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sightType {
            get {
                return this.sightTypeField;
            }
            set {
                this.sightTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hasSight {
            get {
                return this.hasSightField;
            }
            set {
                this.hasSightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gmNotes {
            get {
                return this.gmNotesField;
            }
            set {
                this.gmNotesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string speechMap {
            get {
                return this.speechMapField;
            }
            set {
                this.speechMapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public netrptoolsmaptoolmodelTokenID[] id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("exposedAreaGUID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public netrptoolsmaptoolmodelTokenExposedAreaGUID[] exposedAreaGUID {
            get {
                return this.exposedAreaGUIDField;
            }
            set {
                this.exposedAreaGUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", typeof(entry), IsNullable=false)]
        public entry[][] imageAssetMap {
            get {
                return this.imageAssetMapField;
            }
            set {
                this.imageAssetMapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", typeof(entry), IsNullable=false)]
        public entry[][] sizeMap {
            get {
                return this.sizeMapField;
            }
            set {
                this.sizeMapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ownerList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public netrptoolsmaptoolmodelTokenOwnerList[] ownerList {
            get {
                return this.ownerListField;
            }
            set {
                this.ownerListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("portraitImage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public netrptoolsmaptoolmodelTokenPortraitImage[] portraitImage {
            get {
                return this.portraitImageField;
            }
            set {
                this.portraitImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", typeof(entry), IsNullable=false)]
        public entry[][] state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("store", typeof(entry[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", typeof(entry), IsNullable=false, NestingLevel=1)]
        public entry[][][] propertyMapCI {
            get {
                return this.propertyMapCIField;
            }
            set {
                this.propertyMapCIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", typeof(entry), IsNullable=false)]
        public entry[][] macroPropertiesMap {
            get {
                return this.macroPropertiesMapField;
            }
            set {
                this.macroPropertiesMapField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class netrptoolsmaptoolmodelTokenID {
        
        private string baGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string baGUID {
            get {
                return this.baGUIDField;
            }
            set {
                this.baGUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class netrptoolsmaptoolmodelTokenExposedAreaGUID {
        
        private string baGUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string baGUID {
            get {
                return this.baGUIDField;
            }
            set {
                this.baGUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class netrptoolsmaptoolmodelTokenOwnerList {
        
        private string stringField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @string {
            get {
                return this.stringField;
            }
            set {
                this.stringField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class netrptoolsmaptoolmodelTokenPortraitImage {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entry", typeof(entry))]
        [System.Xml.Serialization.XmlElementAttribute("net.rptools.maptool.model.Token", typeof(netrptoolsmaptoolmodelToken))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
